### ISSUE TITLE
Set icon text to path.

### ISSUE THREAD

**Issue by TraumaD** [aleksandar-stefanovic/urmsimulator#4]
You need to set the text in your icons to paths so that they always display properly.

![screenshot from 2017-07-11 00 39 45](https://user-images.githubusercontent.com/10608836/28052580-7cf14f90-65d1-11e7-95ef-734eda9a8144.png)

**Comment by aleksandar-stefanovic** [comment]
Thank you for the advice, fix coming in ASAP!
